apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- rqlitecluster_autoscaling.yaml
- rqlitecluster_storage_expansion.yaml

namePrefix: autoscaling-
namespace: default

commonLabels:
  example: autoscaling-features